source("./utils_codes/utils.R")
source("./utils_codes/downstream.R")
source("./utils_codes/normalize.R")
source("./utils_codes/hrmf_em.R")
source("./utils_codes/hrmf_init.R")
source("./utils_codes/image_tools.R")

# Spatial CNA Analysis Pipeline
#
# This function performs spatial CNA detection and visualization
# given a Seurat object and spatial transcriptomics data.
#
# @param sample_dir Directory of the sample data (contains `seurat_object.rds` and `gene_pos.rds`).
#   - `seurat_object.rds`: A Seurat object.
#       * Expression matrix stored in `obj@assays$Spatial@counts`.
#       * Contains clustering results from the Seurat standard workflow (in `obj$seurat_clusters`), 
#         or custom cell-type annotations that can be used to define normal reference cells.  
#   - `gene_pos.rds`: A data.frame containing genomic annotation of genes with the following columns:
#       * `symbol`: Gene symbol.
#       * `chr`: Chromosome name (e.g., "chr1").
#       * `start`: Start position of the gene (bp).
#       * `end`: End position of the gene (bp).
#
# @param BICseq_dir Path to the MBICseq executable.
#   - Default is "./code/MBICseq" (relative path inside the package/project).
#   - Users should provide the absolute path to the executable when running in their environment.
#   - MBICseq is used for segmentation in CNA calculation.
#
# @param image_dir Directory containing the image feature results generated by `get_spatial_feature.py`.  
#   The directory must include a subfolder `resnet50/` with the following files:  
#   - `features_pca.txt`: PCA-reduced image feature matrix.  
#   - `features_names.txt`: Feature names corresponding to the PCA features.  
#
# @param plot_dir Output directory for plots and results.
# @param bin_file Path to bin definition file (e.g., "bin_K=1e+06_hg38.RDS").
# @param normal_clusters IDs of clusters in `seurat_object.rds` (`obj$seurat_clusters`) 
#   that represent normal cells to be used as reference.
# @param state_ratio Copy number state ratios (default: c(0.5, 1, 1.5)).
# @param max_iter Maximum iterations for HMRF (default: 5).
# @param beta_fixed Beta parameter for HMRF (default: 5).
# @param update_gaussian Logical. Whether to update the mean and standard deviation of the Gaussian distribution.
# @param tumor_perc Numeric vector indicating the tumor fraction for spots. 
#   This can be estimated using SpaCNA's downstream module. Defaults to 1 for all spots.
#
# @return A list containing processed CNA matrices and intermediate results.

SpaCNA <- function(sample_dir,
                   image_dir,
                   plot_dir,
                   BICseq_dir='./utils_codes/MBICseq',
                   bin_file='./data/bin_K=1e+06_hg38.RDS',
                   data_type="10X",
                   normal_clusters,
                   dlm_dV=0.1, dlm_dW=0.001,
                   state_ratio = c(0.5,1,1.5),
                   max_iter = 5,
                   beta_fixed = 5,
                   tumor_perc=1,
                   update_gaussian=FALSE,
                   lambda=0.003,
                   image_thre=0.2,
                   zero_thre=0.95) {
    
    # Use file.path for cross-platform path handling
    sample_dir <- file.path(sample_dir, "")
    image_dir <- if(image_dir != "") file.path(image_dir, "") else image_dir
    plot_dir <- file.path(plot_dir, "")
    
    # load object
    obj <- readRDS(paste0(sample_dir,"seurat_object.rds"))

    ## inputs
    # count_RNA <- as.matrix(obj@assays$Spatial@counts)
    count_RNA <- tryCatch({
    as.matrix(obj@assays$Spatial@counts)
    }, error = function(e) {
    tryCatch({
        as.matrix(GetAssayData(obj, layer = "counts"))
    }, error = function(e) {
        as.matrix(GetAssayData(obj, slot = "counts"))
    })
    })
    # count_RNA <- as.matrix(obj@assays$Spatial@layers$counts) 
    # rownames(count_RNA) <- rownames(obj) 
    # colnames(count_RNA) <- colnames(obj) 

    zero_prop <- rowSums(count_RNA == 0) / ncol(count_RNA)
    count_RNA <- count_RNA[zero_prop < zero_thre, ]
    count_RNA <- count_RNA[rowMeans(count_RNA)>0.05, ]
    message("Input count matrix dimension: ", paste(dim(count_RNA), collapse=" x "))

    bin <- readRDS(bin_file)
    cell_barcodes <- colnames(count_RNA)
    seurat_cluster <- as.numeric(obj$seurat_clusters)-1
    cluster <- as.character(seurat_cluster)
    # spot_location <- get_spot_location(obj,type=data_type)
    spot_location <- get_spot_location(obj)
    normal_cells <- cell_barcodes[cluster %in% normal_clusters]
    cnv_state_level=length(state_ratio)

    # gene position
    gene_pos <- readRDS(file.path(sample_dir, "gene_pos.rds"))
    gene_pos <- gene_pos[gene_pos$symbol %in% rownames(count_RNA), ]
    gene_pos <- gene_pos[order(as.numeric(substr(gene_pos$chr,4,5)), gene_pos$start), ]
    gene_pos$n <- 1:nrow(gene_pos)

    # count gene number in bins
    gene_num <- rep(0, nrow(bin))
    for(i in 1:nrow(bin)){
        f <- gene_pos$chr==bin$chr[i] & gene_pos$start>=bin$start[i] & gene_pos$end<=bin$end[i]
        gene_num[i] <- sum(f)
    }

    ## gene smooth
    count_RNA <- count_RNA[gene_pos$symbol,]
    count_RNA_smooth <- chr_smooth(count_RNA, log=T, dlm_dV=dlm_dV, dlm_dW=dlm_dW)
    count_RNA_smooth <- edgeR::cpm(count_RNA_smooth)

    expr_neigh<-get_expr_neigh_list(count_RNA_smooth,pca=20,k=10,thre=0.4)

    is_empty <- is.null(image_dir) || 
              length(image_dir) == 0 || 
              image_dir == "" || 
              all(trimws(image_dir) == "")
  
    if (is_empty) {
        neigh_cell <- get_neigh_list_simple(spot_location, k=7)        
    } else {
        neigh_cell <- get_final_neigh(image_dir, spot_location, k=7, thre=image_thre, dist_thre='unknown')
    }
    count_RNA_spa <- spatial_smooth(count_RNA_smooth,
                                    expr_neigh,
                                    neigh_cell,
                                    alpha=c(0.5, 0.25, 0.25))
    count_RNA_norm <- get_copy_ratio(count_RNA_spa, normal_cells)

    count_norm <- generate_bin_count(count_RNA_norm, gene_pos, bin, func=mean)
    count_bin<-generate_bin_count(count_RNA, gene_pos, bin, func=sum)
    f <- gene_num >= 2
    # count_norm <- count_norm[f,]
    count_norm<-preprocess(count_bin[f,],count_norm[f,],bin[f,],thre_bin = 0.8,thre_map = 250000)
    
    if (!dir.exists(plot_dir)) {
        dir.create(plot_dir, recursive = TRUE)
    }
    saveRDS(count_norm, file.path(plot_dir, "count_norm.rds"))
    # plot CNA heatmap
    if (length(cluster)>1000){
        f <- sample(1:length(cluster), 1000)
    }else{
        f <- 1:length(cluster)
    }
    plot_heatmap(t(count_norm)[f,],
                cell_cluster=cluster[f],
                cell_annotation=cluster[f],
                output_dir=plot_dir,
                output_name="copy_ratio.png",
                cnv_state_level=cnv_state_level)

    ## hmrf para init
    parameter_init <- estimate_hmrf_parameter(count_RNA=count_RNA,
                                            normal_cells=normal_cells,
                                            gene_pos=gene_pos,
                                            bin=bin,
                                            gene_normalize=F,
                                            cnv_num=cnv_state_level,
                                            num_cells=200,
                                            tumor_perc=tumor_perc,
                                            common_dispersion=0.1,
                                            dropout_prob="au",
                                            dlm_dV=dlm_dV,
                                            dlm_dW=dlm_dW,
                                            alpha=c(0.5, 0.25, 0.25),
                                            gene_thre=2)
    if(parameter_init[[1]][1]>0.85){
        parameter_init <- estimate_hmrf_parameter(count_RNA=count_RNA,
                                            normal_cells=normal_cells,
                                            gene_pos=gene_pos,
                                            bin=bin,
                                            gene_normalize=F,
                                            cnv_num=cnv_state_level,
                                            num_cells=200,
                                            tumor_perc=tumor_perc,
                                            common_dispersion=0.1,
                                            dropout_prob=0.1,
                                            dlm_dV=dlm_dV,
                                            dlm_dW=dlm_dW,
                                            alpha=c(0.5, 0.25, 0.25),
                                            gene_thre=2)

    }
    saveRDS(parameter_init, file.path(plot_dir, "hrmf_para.rds"))

    ## cn state init
    mus <- parameter_init[[1]]
    sigmas <- parameter_init[[2]]
    if (cnv_state_level==3){
        mus_df <- data.frame(row.names=cell_barcodes,
                            p=rep(tumor_perc, length(cell_barcodes)),
                            mu1=mus[1], mu2=mus[2], mu3=mus[3])
        sigs_df <- data.frame(row.names=cell_barcodes,
                            p=rep(tumor_perc, length(cell_barcodes)),
                            mu1=sigmas[1], mu2=sigmas[2], mu3=sigmas[3])

    }else{
        mus_df <- data.frame(row.names=cell_barcodes,
                            p=rep(tumor_perc, length(cell_barcodes)),
                            mu1=mus[1], mu2=mus[2], mu3=mus[3],mu4=mus[4], mu5=mus[5])
        sigs_df <- data.frame(row.names=cell_barcodes,
                            p=rep(tumor_perc, length(cell_barcodes)),
                            mu1=sigmas[1], mu2=sigmas[2], mu3=sigmas[3], mu4=sigmas[4], mu3=sigmas[5])

    }

    cnv_state <- get_cnv_init_perce(count_norm, mus_df, sigs_df)
    cnv_state_init <- state2ratio(cnv_state, state_ratio)

    plot_heatmap(t(cnv_state_init)[f,],
                cell_annotation=cluster[f],
                output_dir=plot_dir,
                output_name="cns_init.png",
                cnv_state_level=cnv_state_level)

    ## segment
    baseline <- rowMeans(count_norm[,normal_cells])

    bk_bic <- calculate_CNV(t(count_norm),
                        baseline,
                        lambda=lambda,
                        sample_dir=plot_dir,
                        BICseq_dir=BICseq_dir)
    saveRDS(bk_bic, file.path(plot_dir, "bk_bic.rds"))

    ## hmrf final
    cns <- get_state_icm_seg_perc(count_norm,
                                bk_bic,
                                neigh_list=neigh_cell,
                                mus_df=mus_df,
                                sigmas_df=sigs_df,
                                max_iter=max_iter,
                                beta_fixed=beta_fixed,
                                update_gaussian=update_gaussian)
    cns_ <- cns
    cns <- state2ratio(cns_, state_ratio)
    saveRDS(cns, file.path(plot_dir, "cns.rds"))

    cns <- denoise(cns, thre=0.98)
    plot_heatmap(t(cns),
                cell_cluster=cluster,
                cell_annotation=cluster,
                output_dir=plot_dir,
                output_name="cns.png",
                cnv_state_level=cnv_state_level)

    message("✅ SpaCNA finished! Results saved in: ", plot_dir)

    return(list(
        count_norm = count_norm,
        parameter_init = parameter_init,
        cnv_state_init = cnv_state_init,
        bk_bic = bk_bic,
        cns = cns
    ))
}

# CLI Wrapper function
run_spacna_cli <- function() {
    # Parse command line arguments
    args <- commandArgs(trailingOnly = TRUE)
    
    # Default values
    sample_dir <- ""
    image_dir <- ""
    plot_dir <- ""
    normal_clusters <- c(0, 1, 3, 8)
    dlm_dV <- 0.1
    dlm_dW <- 0.001
    image_thre <- 0.2
    
    # Parse arguments
    for (arg in args) {
        if (grepl("^--sample_dir=", arg)) {
            sample_dir <- sub("^--sample_dir=", "", arg)
        } else if (grepl("^--image_dir=", arg)) {
            image_dir <- sub("^--image_dir=", "", arg)
        } else if (grepl("^--plot_dir=", arg)) {
            plot_dir <- sub("^--plot_dir=", "", arg)
        } else if (grepl("^--normal_clusters=", arg)) {
            cluster_str <- sub("^--normal_clusters=", "", arg)
            normal_clusters <- as.numeric(unlist(strsplit(cluster_str, ",")))
        } else if (grepl("^--dlm_dV=", arg)) {
            dlm_dV <- as.numeric(sub("^--dlm_dV=", "", arg))
        } else if (grepl("^--dlm_dW=", arg)) {
            dlm_dW <- as.numeric(sub("^--dlm_dW=", "", arg))
        } else if (grepl("^--image_thre=", arg)) {
            image_thre <- as.numeric(sub("^--image_thre=", "", arg))
        }
    }
    
    # Validate required argument
    if (sample_dir == "" || plot_dir == "") {
        stop("Error: --sample_dir and --plot_dir arguments are required.")
    }
    
    # Run SpaCNA
    cna_list <- SpaCNA(sample_dir = sample_dir,
                       image_dir = image_dir,
                       plot_dir = plot_dir,
                       normal_clusters = normal_clusters,
                       dlm_dV = dlm_dV,
                       dlm_dW = dlm_dW,
                       image_thre = image_thre)
    
    return(cna_list)
}

# Execute CLI if called from command line
if (!interactive() && length(commandArgs(trailingOnly = TRUE)) > 0) {
    run_spacna_cli()
}

# For backward compatibility - example usage
if (FALSE) {
    # Original style (users can still edit these variables if needed)
    sample_dir <- ""
    image_dir <- ""
    plot_dir <- ""
    
    # Run analysis
    cna_list <- SpaCNA(sample_dir, image_dir, plot_dir, 
                       normal_clusters = c(0, 1, 3, 8), 
                       dlm_dV = 0.1, dlm_dW = 0.001,image_thre=0.2)
}